def raise_exception():
    raise "Exception has been raised"