def raise_exception():
    raise "Exception Raised"